spring:
  data:
    mongodb:
      uri: mongodb+srv://<Username>:<Password>@cluster0.tdga3ht.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: recommendationsdb
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  gemini:
    api:
      url: ${GEMINI_API_URL}
      key: ${GEMINI_API_KEY}

server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.routing
